[09/09/2016 22:20] INFO economy _set 268: BlakeDevs(209497824155533332) set 1000 credits to BlakeDevs (209497824155533332)
[09/09/2016 22:23] ERROR red on_command_error 88: Exception in command 'version'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 542, in version
    result = await asyncio.wait_for(response, timeout=10)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 392, in wait_for
    return fut.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 605, in _get_version
    *version)
IndexError: tuple index out of range
[09/09/2016 23:56] ERROR red load_cogs 348: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 20, 19, '\t\tself.rbxrap = {}\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 20
    self.rbxrap = {}
                   ^
TabError: inconsistent use of tabs and spaces in indentation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 20, 19, '\t\tself.rbxrap = {}\n'))
[10/09/2016 00:00] ERROR red load_cogs 348: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 20, 19, '\t\tself.rbxrap = {}\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 20
    self.rbxrap = {}
                   ^
TabError: inconsistent use of tabs and spaces in indentation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 20, 19, '\t\tself.rbxrap = {}\n'))
[10/09/2016 00:01] ERROR red load_cogs 348: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 141, 22, '\t\t@commands.command()\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 141
    @commands.command()
                      ^
TabError: inconsistent use of tabs and spaces in indentation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 141, 22, '\t\t@commands.command()\n'))
[10/09/2016 00:04] ERROR red load_cogs 348: ('unexpected indent', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 142, 8, '        async def rbxrap(self, user : str):\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 142
    async def rbxrap(self, user : str):
    ^
IndentationError: unexpected indent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('unexpected indent', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 142, 8, '        async def rbxrap(self, user : str):\n'))
[10/09/2016 00:06] ERROR red load_cogs 348: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 145, 21, '\t     j = rap.json()\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145
    j = rap.json()
                 ^
TabError: inconsistent use of tabs and spaces in indentation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 145, 21, '\t     j = rap.json()\n'))
[10/09/2016 00:13] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145, in rbxrap
    await self.bot.say(rapd[0]['rap'])
TypeError: 'Response' object does not support indexing
[10/09/2016 00:18] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = json.loads('http://roblox.plus:2052/inventory?username='.format(user))
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[10/09/2016 00:19] ERROR red load_cogs 348: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 145, 22, '\t\t jlo = json.load(j)\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145
    jlo = json.load(j)
                     ^
TabError: inconsistent use of tabs and spaces in indentation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 145, 22, '\t\t jlo = json.load(j)\n'))
[10/09/2016 00:20] ERROR red load_cogs 348: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 146, 22, '\t\t jlo = json.load(j)\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 146
    jlo = json.load(j)
                     ^
TabError: inconsistent use of tabs and spaces in indentation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 146, 22, '\t\t jlo = json.load(j)\n'))
[10/09/2016 00:21] ERROR red load_cogs 348: No module named 'urllib2'
Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 8, in <module>
    import urllib2
ImportError: No module named 'urllib2'
[10/09/2016 00:22] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = json.load('http://roblox.plus:2052/inventory?username='.format(user))
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\json\__init__.py", line 265, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
[10/09/2016 00:24] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = json.load('http://roblox.plus:2052/inventory?username='.format(user).read())
AttributeError: 'str' object has no attribute 'read'
[10/09/2016 00:26] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = json.loads('http://roblox.plus:2052/inventory?username='.format(user))
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[10/09/2016 00:29] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145, in rbxrap
    await self.bot.say(j.rap)
AttributeError: 'dict' object has no attribute 'rap'
[10/09/2016 00:33] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145, in rbxrap
    await self.bot.say(j[0]['rap'])
KeyError: 0
[10/09/2016 00:37] ERROR red load_cogs 348: ('unindent does not match any outer indentation level', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 144, 93, "         j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json()\n"))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json()
                                                                                      ^
IndentationError: unindent does not match any outer indentation level

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('unindent does not match any outer indentation level', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 144, 93, "         j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json()\n"))
[10/09/2016 00:38] ERROR red load_cogs 348: ('unindent does not match any outer indentation level', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 144, 93, "         j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json()\n"))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json()
                                                                                      ^
IndentationError: unindent does not match any outer indentation level

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('unindent does not match any outer indentation level', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 144, 93, "         j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json()\n"))
[10/09/2016 00:39] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    await self.bot.say(j.rap)
AttributeError: 'dict' object has no attribute 'rap'
[10/09/2016 00:40] ERROR red load_cogs 348: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 144, 10, '\t\t t = {}\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144
    t = {}
         ^
TabError: inconsistent use of tabs and spaces in indentation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 144, 10, '\t\t t = {}\n'))
[10/09/2016 00:41] ERROR red load_cogs 348: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 144, 9, '\t t = {}\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144
    t = {}
         ^
TabError: inconsistent use of tabs and spaces in indentation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 144, 9, '\t t = {}\n'))
[10/09/2016 00:41] ERROR red load_cogs 348: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 144, 9, '\t t = []\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144
    t = []
         ^
TabError: inconsistent use of tabs and spaces in indentation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 144, 9, '\t t = []\n'))
[10/09/2016 00:45] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json().json_dump(data)
AttributeError: 'dict' object has no attribute 'json_dump'
[10/09/2016 00:47] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json().json_dump(data)
AttributeError: 'dict' object has no attribute 'json_dump'
[10/09/2016 00:48] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json(data)
NameError: name 'data' is not defined
[10/09/2016 00:49] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json(rap)
NameError: name 'rap' is not defined
[10/09/2016 00:50] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json(data)
NameError: name 'data' is not defined
[10/09/2016 00:51] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json(data)
UnboundLocalError: local variable 'data' referenced before assignment
[10/09/2016 00:52] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json(data)
TypeError: json() takes 1 positional argument but 2 were given
[10/09/2016 00:53] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json(data, true)
TypeError: json() takes 1 positional argument but 2 were given
[10/09/2016 00:53] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json().json_dump(data)
TypeError: json() takes 1 positional argument but 2 were given
[10/09/2016 00:53] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json().json_dump(data)
AttributeError: 'dict' object has no attribute 'json_dump'
[10/09/2016 00:54] ERROR red load_cogs 348: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 145, 20, '\t\t a = json_dump(j)\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145
    a = json_dump(j)
                   ^
TabError: inconsistent use of tabs and spaces in indentation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 145, 20, '\t\t a = json_dump(j)\n'))
[10/09/2016 00:55] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145, in rbxrap
    a = json_dump(j)
NameError: name 'json_dump' is not defined
[10/09/2016 00:56] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json(data, true)
NameError: name 'true' is not defined
[10/09/2016 00:56] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json(data)
TypeError: json() takes 1 positional argument but 2 were given
[10/09/2016 00:58] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json(self, data)
TypeError: json() takes 1 positional argument but 3 were given
[10/09/2016 01:00] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145, in rbxrap
    n = json_decode(j)
NameError: name 'json_decode' is not defined
[10/09/2016 13:01] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145, in rbxrap
    k = json_loads(j)
NameError: name 'json_loads' is not defined
[10/09/2016 13:02] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145, in rbxrap
    k = json_loads(j)
NameError: name 'json_loads' is not defined
[10/09/2016 13:02] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145, in rbxrap
    k = json_load(j)
NameError: name 'json_loads' is not defined
[10/09/2016 13:05] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json().json_dump(data)
AttributeError: 'dict' object has no attribute 'json_dump'
[10/09/2016 13:05] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(user)).json().data
AttributeError: 'dict' object has no attribute 'data'
[10/09/2016 13:05] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145, in rbxrap
    r = json_loads(j)
NameError: name 'json_loads' is not defined
[10/09/2016 13:08] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145, in rbxrap
    r = json_load(j)
NameError: name 'json_load' is not defined
[10/09/2016 13:10] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    response = urllib.urlopen(j)
AttributeError: module 'urllib' has no attribute 'urlopen'
[10/09/2016 13:12] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    response = urlopen(j)
NameError: name 'urlopen' is not defined
[10/09/2016 13:15] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 150, in rbxrap
    response = urlopen(j)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[10/09/2016 13:18] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145, in rbxrap
    n = json_decode(j)
NameError: name 'json_decode' is not defined
[10/09/2016 13:18] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145, in rbxrap
    k = json_loads(j)
NameError: name 'json_loads' is not defined
[10/09/2016 13:24] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.print(user)).json()
AttributeError: 'str' object has no attribute 'print'
[10/09/2016 13:27] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.print(username)).json()
AttributeError: 'str' object has no attribute 'print'
[10/09/2016 13:32] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.str(print(user))).json()
AttributeError: 'str' object has no attribute 'str'
[10/09/2016 13:33] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.username).json()
AttributeError: 'str' object has no attribute 'username'
[10/09/2016 13:34] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.user).json()
AttributeError: 'str' object has no attribute 'user'
[10/09/2016 13:35] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    user = eval(username)
  File "<string>", line 1, in <module>
NameError: name 'LordDamionDevil' is not defined
[10/09/2016 13:36] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.eval(username)).json()
AttributeError: 'str' object has no attribute 'eval'
[10/09/2016 13:37] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    user = eval(username)
  File "<string>", line 1, in <module>
NameError: name 'LordDamionDevil' is not defined
[10/09/2016 13:40] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    user = raw_input(username)
NameError: name 'raw_input' is not defined
[10/09/2016 13:40] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    user = raw_input(username)
NameError: name 'raw_input' is not defined
[10/09/2016 13:42] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    user = eval(username)
  File "<string>", line 1, in <module>
NameError: name 'LordDamionDevil' is not defined
[10/09/2016 13:43] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    user = eval(username)
  File "<string>", line 1, in <module>
NameError: name 'LordDamionDevil' is not defined
[10/09/2016 13:45] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.user).json()
AttributeError: 'str' object has no attribute 'user'
[10/09/2016 13:45] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.username).json()
AttributeError: 'str' object has no attribute 'username'
[10/09/2016 13:46] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.print(user)).json()
AttributeError: 'str' object has no attribute 'print'
[10/09/2016 13:47] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    user = eval(rip)
  File "<string>", line 1, in <module>
NameError: name 'LordDamionDevil' is not defined
[10/09/2016 13:48] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    user = eval(rip)
  File "<string>", line 1, in <module>
NameError: name 'LordDamionDevil' is not defined
[10/09/2016 13:49] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.rip).json()
AttributeError: 'str' object has no attribute 'rip'
[10/09/2016 13:52] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    rip = exec(username)
  File "<string>", line 1, in <module>
NameError: name 'LordDamionDevil' is not defined
[10/09/2016 13:53] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    rip = exec(username)
  File "<string>", line 1, in <module>
NameError: name 'LordDamionDevil' is not defined
[10/09/2016 13:59] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    rip = eval(username)
  File "<string>", line 1, in <module>
NameError: name 'LordDamionDevil' is not defined
[10/09/2016 14:01] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.eval(username)).json()
AttributeError: 'str' object has no attribute 'eval'
[10/09/2016 14:01] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.exec(username)).json()
AttributeError: 'str' object has no attribute 'exec'
[10/09/2016 14:02] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.raw_input(username)).json()
AttributeError: 'str' object has no attribute 'raw_input'
[10/09/2016 14:03] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    dd = raw_input(username)
NameError: name 'raw_input' is not defined
[10/09/2016 14:08] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    dd = eval(print(username))
TypeError: eval() arg 1 must be a string, bytes or code object
[10/09/2016 14:09] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    dd = eval(format(username))
  File "<string>", line 1, in <module>
NameError: name 'LordDamionDevil' is not defined
[10/09/2016 14:10] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 143, in rbxrap
    dd = eval(str.format(username))
  File "<string>", line 1, in <module>
NameError: name 'LordDamionDevil' is not defined
[10/09/2016 14:11] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.dd).json()
AttributeError: 'str' object has no attribute 'dd'
[10/09/2016 14:11] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.eval(dd)).json()
AttributeError: 'str' object has no attribute 'eval'
[10/09/2016 14:13] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.print(dd)).json()
AttributeError: 'str' object has no attribute 'print'
[10/09/2016 14:16] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(d),eval(dd)).json()
  File "<string>", line 1, in <module>
NameError: name 'LordDamionDevil' is not defined
[10/09/2016 14:17] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.str.format(dd)).json()
AttributeError: 'str' object has no attribute 'str'
[10/09/2016 14:18] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144, in rbxrap
    j = requests.get('http://roblox.plus:2052/inventory?username='.format(dd)).json()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[10/09/2016 14:27] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 146, in rbxrap
    j = r.json()
AttributeError: '_DetachedRequestContextManager' object has no attribute 'json'
[10/09/2016 14:30] ERROR red load_cogs 348: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 144, 35, '\t\t username = str.format(username)\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 144
    username = str.format(username)
                                  ^
TabError: inconsistent use of tabs and spaces in indentation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 144, 35, '\t\t username = str.format(username)\n'))
[10/09/2016 14:31] ERROR red load_cogs 348: ('unexpected indent', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 148, 20, '                    await self.bot.say(result)\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 148
    await self.bot.say(result)
    ^
IndentationError: unexpected indent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('unexpected indent', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 148, 20, '                    await self.bot.say(result)\n'))
[10/09/2016 14:32] ERROR red load_cogs 348: ('expected an indented block', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 146, 14, '         async with aiohttp.get(url) as r:\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 146
    async with aiohttp.get(url) as r:
        ^
IndentationError: expected an indented block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('expected an indented block', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 146, 14, '         async with aiohttp.get(url) as r:\n'))
[10/09/2016 14:33] ERROR red load_cogs 348: ('expected an indented block', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 147, 17, '           result = await r.json()\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 147
    result = await r.json()
         ^
IndentationError: expected an indented block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('expected an indented block', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 147, 17, '           result = await r.json()\n'))
[10/09/2016 14:35] ERROR red load_cogs 348: ('unexpected unindent', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 150, 4, '    @commands.command(no_pm=True, hidden=True)\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 150
    @commands.command(no_pm=True, hidden=True)
    ^
IndentationError: unexpected unindent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('unexpected unindent', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 150, 4, '    @commands.command(no_pm=True, hidden=True)\n'))
[10/09/2016 14:36] ERROR red load_cogs 348: ('unexpected unindent', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 150, 4, '    @commands.command(no_pm=True, hidden=True)\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 150
    @commands.command(no_pm=True, hidden=True)
    ^
IndentationError: unexpected unindent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('unexpected unindent', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 150, 4, '    @commands.command(no_pm=True, hidden=True)\n'))
[10/09/2016 14:40] ERROR red load_cogs 348: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 145, 57, '\t\t self.bot.say("Fetching ROBLOX Rap from ROBLOX+ API!")\n'))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 549, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 145
    self.bot.say("Fetching ROBLOX Rap from ROBLOX+ API!")
                                                        ^
TabError: inconsistent use of tabs and spaces in indentation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 553, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('inconsistent use of tabs and spaces in indentation', ('C:\\Users\\User\\Desktop\\Red-DiscordBot-develop\\cogs\\general.py', 145, 57, '\t\t self.bot.say("Fetching ROBLOX Rap from ROBLOX+ API!")\n'))
[10/09/2016 14:48] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 148, in rbxrap
    await self.bot.say(result['username'] + "'s Rap is " + result['rap'])
TypeError: Can't convert 'int' object to str implicitly
[10/09/2016 14:48] ERROR red on_command_error 88: Exception in command 'rbxrap'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\general.py", line 148, in rbxrap
    await self.bot.say(result['username'] + "'s Rap is " + result['rap'])
TypeError: Can't convert 'int' object to str implicitly
[10/09/2016 16:22] INFO economy _set 268: LordDamionDevil(82662823523516416) set 500 credits to LordDamionDevil (82662823523516416)
[10/09/2016 16:34] INFO economy _set 268: LordDamionDevil(82662823523516416) set 5000 credits to Silicti (196057269128003584)
[10/09/2016 21:25] ERROR red on_command_error 88: Exception in command 'disconnect'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\audio.py", line 1114, in disconnect
    await self._stop_and_disconnect(server)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\audio.py", line 911, in _stop_and_disconnect
    await self._disconnect_voice_client(server)
  File "C:\Users\User\Desktop\Red-DiscordBot-develop\cogs\audio.py", line 391, in _disconnect_voice_client
    await voice_client.disconnect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 271, in disconnect
    yield from self.ws.close()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 239, in close
    self.worker, self.timeout, loop=self.loop)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 392, in wait_for
    return fut.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 411, in run
    msg = yield from self.read_message()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 433, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 488, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 523, in read_frame
    self.reader.readexactly, is_masked, max_size=max_size)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\framing.py", line 80, in read_frame
    data = yield from reader(2)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\asyncio\streams.py", line 670, in readexactly
    block = yield from self.read(n)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\asyncio\streams.py", line 627, in read
    yield from self._wait_for_data('read')
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\asyncio\streams.py", line 457, in _wait_for_data
    yield from self._waiter
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 296, in _wakeup
    future.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\asyncio\selector_events.py", line 669, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
